---
title: Notepad
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Blogging is fun
logo: logo3.png
disqus_shortname: hmfaysal
share: true
owner:
  name: Your Name
  avatar: hmfaysal.jpg
  email: you@email.com
  description: Awesome Dude, Awesome Life
  twitter: hmfaysal
  facebook: hmfaysal
  github: hmfaysal
  instagram: hmfaysal
  google_plus: https://plus.google.com/u/0/102602916593522619858
google_analytics: 
google_verify: 
bing_verify: 
links:
- title: Home
  url: "/"
  external: false
  icon: home
- title: Featured Posts
  url: "/featured"
- title: Categories
  url: "/categories"
- title: About
  url: "/hossain-mohd-faysal"
future: true
highlighter: pygments
markdown: kramdown
paginate: 5
paginate_path: page:num
permalink: "/:categories/:title"
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class
prose:
  rooturl: _posts
  siteurl: http://hmfaysal.github.io/
  relativeLinks: http://hmfaysal.github.io/links.jsonp
  media: images
  metadata:
    _posts:
    - name: published
      field:
        label: Published
        element: checkbox
        value: 'true'
    - name: layout
      field:
        element: hidden
        label: Layout
        value: post
    - name: title
      field:
        label: Title
        element: text
        value: An Awesome Headline!
    - name: description
      field:
        element: text
        label: Description
        placeholder: Enter Post Description
    - name: headline
      field:
        element: text
        label: beadline
        placeholder: Enter Post Headline
    - name: modified
      field:
        element: text
        label: Has this page been modified?
        placeholder: YYYY-MM-DD
    - name: categories
      field:
        element: multiselect
        label: Add categories
        placeholder: Choose categories
        value: personal
        options:
        - name: Personal
          value: personal
        - name: Engineering
          value: engineering
        - name: Physics
          value: physics
        - name: Psychology
          value: psychology
        - name: Interesting
          value: interesting
        - name: Web-Development
          value: webdevelopment
        alterable: true
    - name: tags
      field:
        element: text
        label: Tags
        placeholder: Enter tags, separated by spaces
    - name: imagefeature
      field:
        element: text
        label: Featured Image
        placeholder: somefile.jpg
    - name: mathjax
      field:
        element: checkbox
        label: MathJax
        value: false
    - name: featured
      field:
        element: checkbox
        label: Featured?
        value: false
    - name: comments
      field:
        element: checkbox
        label: Comments
        value: false
include:
- ".htaccess"
exclude:
- lib
- config.rb
- Gemfile
- Capfile
- Gemfile.lock
- config
- log
- Rakefile
- Rakefile.rb
- tmp
- less
- "*.sublime-project"
- "*.sublime-workspace"
- test
- spec
- Gruntfile.js
- package.json
- node_modules
